# -*- coding: utf-8 -*-
"""circet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YlVZYwgQymcJ8tXukTHLY69vSJXg2dnF
"""

import pandas as pd

# ============================================================
#         CRICKET PLAYER SCORES ANALYZER
#         Using Pandas Series Only
# ============================================================

print("=" * 45)
print("      CRICKET PLAYER SCORES ANALYZER")
print("=" * 45)

# ── STEP 1: 5 matches ke scores ─────────────────────────────
# Ek player ne 5 matches mein ye runs banaye
babar  = pd.Series([85, 120, 45, 90, 110], index=['Match1','Match2','Match3','Match4','Match5'])
rizwan = pd.Series([60, 75,  80, 55,  95], index=['Match1','Match2','Match3','Match4','Match5'])
fakhar = pd.Series([30, 140, 20, 70,  50], index=['Match1','Match2','Match3','Match4','Match5'])

print("\n🏏 Har Player ke Scores:\n")
print("Babar Azam:")
print(babar.to_string())
print("\nRizwan:")
print(rizwan.to_string())
print("\nFakhar Zaman:")
print(fakhar.to_string())

# ── STEP 2: Har player ki basic stats ───────────────────────
print("\n" + "=" * 45)
print("  PLAYER STATS SUMMARY")
print("=" * 45)
print(f"\n{'Player':<14} {'Total':>7} {'Average':>9} {'Best':>7} {'Worst':>7}")
print("-" * 45)

players = {"Babar Azam": babar, "Rizwan": rizwan, "Fakhar Zaman": fakhar}

for name, scores in players.items():
    print(f"  {name:<12} {scores.sum():>7} {scores.mean():>8.1f} {scores.max():>7} {scores.min():>7}")

# ── STEP 3: Best match dhundho ───────────────────────────────
print("\n" + "=" * 45)
print("  BEST SCORE - KIS MATCH MEIN?")
print("=" * 45)

for name, scores in players.items():
    best_match = scores.idxmax()
    best_score = scores.max()
    print(f"\n  {name}: {best_score} runs  ->  {best_match} mein!")

# ── STEP 4: Filter - 50+ scores (Half Century) ──────────────
print("\n" + "=" * 45)
print("  HALF CENTURIES (50+ runs)")
print("=" * 45)

for name, scores in players.items():
    fifties = scores[scores >= 50]
    print(f"\n  {name}: {fifties.count()} half centuries")
    print(fifties.to_string())

# ── STEP 5: Total team score per match ──────────────────────
print("\n" + "=" * 45)
print("  TEAM TOTAL PER MATCH")
print("=" * 45)

team_total = babar + rizwan + fakhar
print()
print(team_total.to_string())
print(f"\n  Best team match  ->  {team_total.idxmax()}  ({team_total.max()} runs!)")

# ── STEP 6: Ek player ki missing score ──────────────────────
print("\n" + "=" * 45)
print("  MISSING SCORE FIX  (Injury ki wajah se)")
print("=" * 45)

shaheen = pd.Series([15, None, 8, None, 20], index=['Match1','Match2','Match3','Match4','Match5'])
print(f"\n  Shaheen ke scores (2 matches mein injured tha):")
print(shaheen.to_string())
print(f"\n  Missing scores: {shaheen.isnull().sum()}")
shaheen_fixed = shaheen.fillna(0)
print(f"\n  Missing ko 0 se fill kiya (did not bat):")
print(shaheen_fixed.to_string())

print("\n" + "=" * 45)
print("  PROJECT COMPLETE! Pakistan Zindabad!")
print("=" * 45)